---
title: "Aspects juridiques et réglementaires du big data : un retour d'expérience"
subtitle: |
  **[BCEAO - Jour 4]{.orange}**
author: "[Romain Avouac](https://github.com/avouacr), [Thomas Faria](https://github.com/ThomasFaria)", [Antoine Palazzolo ](https://github.com/antoine-palazz)"
date: "09/28/2023"
date-format: "D MMMM YYYY"
slide-number: true
lang: fr-FR
# for blind readers:
slide-tone: false
chalkboard: # press the B key to toggle chalkboard
  theme: whiteboard
# uncomment to use the multiplex mode:
# multiplex: true
format:
  onyxia-revealjs:
    output-file: index.html
controls: true
css: ../custom.css
from: markdown+emoji
ascii: true
execute: 
  echo: false
  warning: false
---

# :one: Introduction

{{< include sections/1-introduction.qmd >}}

{{< include sections/2-juridique.qmd >}}

{{< include sections/3-scrapping-insee.qmd >}}

Patrick rudor UAJC
voir avec eux

Webscrapping + attention RGPD
slide sur les LLM avec les contentieux en cours (OpenAI) + modele de diffusion avec les artistes
questions des données générées

1- Les nouveaux enjeux juridiques du big data

Collecte des données
Stockage des données (souveraineté)
Traitements des données
Partage de données


Data Ownership 
Open Data & Public Sector 
Database Licensing 
Copyright Infringement 
Security Breaches
le cas du webscrapping
Aujourd'hui : cas des LLM (contentieux en cours avec OpenAI) + cas des modèles de diffusion avec les artistes + cas données générées (pb Amazon)

2- Réglementations clés

  Loi modernisation du numérque 2016 : https://www.vie-publique.fr/eclairage/20301-loi-republique-numerique-7-octobre-2016-loi-lemaire-quels-changements

  Règlement Général sur la Protection des Données (RGPD) de l'UE : https://fr.wikipedia.org/wiki/R%C3%A8glement_g%C3%A9n%C3%A9ral_sur_la_protection_des_donn%C3%A9es#
  Loi sur la Protection de la Vie Privée en Ligne (CCPA) de Californie : https://fr.wikipedia.org/wiki/Loi_californienne_sur_la_protection_de_la_vie_priv%C3%A9e_des_consommateurs

3- Retour d'expériences à l'insee

- Webscrapping à l'Insee
- Mobitic ? Cnis doit valider besoin
- 























I. Introduction

    Définition du Big Data et son importance croissante dans notre société.
    Objectif de la présentation : Examiner les questions légales soulevées par le Big Data et illustrer ces problèmes par des exemples concrets.

II. Collecte de Données

    Risque : Consentement et Confidentialité
        Exemple : Une application de fitness collecte des données biométriques sans le consentement explicite de ses utilisateurs, ce qui peut violer les réglementations sur la protection des données.

III. Stockage de Données

    Risque : Sécurité des Données
        Exemple : Une entreprise de stockage en nuage subit une violation de données, exposant ainsi les informations sensibles de ses clients, ce qui peut entraîner des poursuites pour négligence.

IV. Traitement de Données

    Risque : Discrimination et Biais Algorithmiques
        Exemple : Un algorithme de recrutement favorise systématiquement un certain groupe démographique, ce qui peut entraîner des accusations de discrimination.

V. Partage de Données

    Risque : Partage Non Autorisé ou Illégal
        Exemple : Une entreprise partage des données client avec des tiers sans obtenir l'autorisation appropriée, ce qui peut violer les lois sur la protection des données.

VI. Analyse de Données et Profilage

    Risque : Violation de la Vie Privée
        Exemple : Une société de médias sociaux analyse les comportements en ligne de ses utilisateurs pour vendre des publicités ciblées, suscitant des préoccupations quant à la vie privée des individus.

VII. Règlementations Clés

    Règlement Général sur la Protection des Données (RGPD) de l'UE
    Loi sur la Protection de la Vie Privée en Ligne (CCPA) de Californie
    Loi sur la Protection des Données Personnelles du Brésil (LGPD)

VIII. Mesures de Conformité

    Collecte de consentements appropriés
    Sécurisation des données
    Évaluation et réduction des biais algorithmiques
    Contrôles d'accès et de partage de données

IX. Conclusion

    Récapitulation des risques et problèmes juridiques liés au Big Data.
    Appel à l'importance de la conformité réglementaire et de l'éthique dans l'utilisation du Big Data.

X. Questions et Discussion





