project:
  type: website
  render:
    - /slides/*/*.qmd
    - index.qmd
    - /cards/*.qmd

website:
  page-navigation: true
  title: "Formation BCEAO"
  site-url: "https://inseefrlab.github.io/formation-bceao/"

  repo-url: "https://github.com/InseeFrLab/formation-bceao"
  # repo-actions: [edit, issue]

  open-graph: true

  page-footer:
    left: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    right:
    - text: "License"
      href: LICENCE.md

  navbar:
    logo: https://upload.wikimedia.org/wikipedia/fr/thumb/1/10/Logo_Insee.svg/1200px-Logo_Insee.svg.png
    align: center
    title: false
    collapse-below: lg

    right:
      - icon: github
        href: "https://github.com/InseeFrLab/formation-bceao"
        aria-label: GitHub

    left:
      - href: index.qmd
        text: Accueil
  
  # twitter-card:
  #   image: /cards/version-light/cheetah.png

format:
  html:
    theme:
      light: [cosmo, style/styles.scss]
      dark: [cyborg, style/styles.scss]
    reference-location: margin
    toc: true
    code-copy: true
    code-overflow: wrap
    include-in-header: "style/fontawesome.html"
