## Context


- [**Plusieurs changements majeurs**]{.orange}:
    - [**Interne**]{.blue2}: Refonte du répertoire [**Sirene 4**]{.green2}.
    - [**Externe**]{.blue2}: Mise en place d’un [**guichet unique**]{.green2} pour déclarer les créations d'entreprises.

- [**Constat**]{.orange}: [**Sicore**]{.blue2} n’est plus l’outil adapté ➨ seulement 30% de codification automatique.

- [**Conséquence**]{.orange}: moment idéal pour proposer une nouvelle méthodologie de codification automatique de l’APE.

## Données

- [$\approx$ **10 million**]{.orange} de liasses d’entreprises issues de Sirene 3 couvrant la période 2014-2022.
- [**Données labellisées**]{.orange} par Sicore ou par un gestionnaire.

- Une observation consiste en :
    - Un [**descriptif textuel**]{.red2} de l'activité
    - La [**nature de l’activité**]{.blue2} -- [NAT]{.green2} (23 modalités)
    - Le [**type de la liasse**]{.blue2} -- [TYP]{.green2} (15 modalités)
    - Le [**type d’évènement**]{.blue2} -- [EVT]{.green2} (24 modalités)
    - La [**surface ($m^2$)**]{.blue2} -- [SUR]{.green2} (4 modalités)
  
## La nomenclature hiérarchique de l'APE

| Niveau | Code | Libellé | Taille |
|-------|------|----------------------|-|
| Section     | H     |Transports et entreposage|21|
| Division    | 52    |Entreposage et services auxiliaires des transports|88|
| Groupe      | 522   |Services auxiliaires des transports|272|
| Classe      | 5224  |Manutention|615|
| **Sous-classe** | [**5224A**]{.red2} |**Manutention portuaire**|[**732**]{.orange}|