## Collecte des données

- Nombreux acteurs privés et publics peuvent collecter des données produites [**directement**]{.orange} ou [**indirectement**]{.orange} par les individus.
- Collecte de données personnelles sans [**consentement**]{.orange} explicite.
- Possibilité de violation de la [**vie privée**]{.orange} des utilisateurs.
- ➡️ Explication des [**motifs**]{.orange} et [**intentions**]{.orange} de collecte des données nécessaire.

::: {.callout-tip title="Exemple de risque potentiel"}
Application de santé collectant des données biométriques de ses utilisateurs sans leur consentement explicite.
:::

## Croissance du numérique

- image de l'intro pour trnasition sur le stockage


## Stockage et sécurité des données

- [**Volume**]{.orange} des données pose la difficulté du stockage.
- [**Coûts d'investissement**]{.orange} importants et marché monopolisé par les GAFAM.
- Problématique de la [**souveraineté numérique**]{.orange}.
- ➡️ Mesures de [**sécurité**]{.orange} essentielles pour la protection des données.

::: {.callout-tip title="Exemple de risque potentiel"}
- Possibilité de violation de la sécurité des données ou de partage de données avec une entité gouvernementale.
- [Incendie OVH](https://fr.wikipedia.org/wiki/Incendie_du_centre_de_donn%C3%A9es_d%27OVHcloud_%C3%A0_Strasbourg) en janvier 2023.
:::

## Open Data et secteur public

- Mise à disposition [**publiquement**]{.orange} et [**gratuitement**]{.orange} des données.
  - En France, [loi Lemaire 2016](https://) : <!-- TODO:  -->
  - Open Data des [**autorités publiques**]{.orange} dans un cadre reglementé.
- Objectif double :cible: :
  - :one: [**Transparence**]{.orange} démocratique et [**ouverture d’information**]{.orange}.
  - :two: Favoriser l'[**innovation**]{.orange} économique et sociale.
- L'Open Data se démocratise aussi dans le secteur privé !


## Propriété intellectuelle

- Gestion des [**licences**]{.orange} :copyright: : 
    - Développement de l'[**open source**]{.blue2} et du partage de données.
    - Nécessité d'apposer et de respecter des licences claires.

- Equilibre difficile entre [**protection**]{.orange} et [**innovation**]{.orange} ⚖️ :
    - Les lois sur le [**droit d'auteur**]{.blue2} établies ont du mal à prendre en compte les nouvelles technologies
    - Développement de [**nouveaux outils**]{.blue2} d'Intelligence Artificielle (IA)

## Des méthodologies toujours plus innovantes...

- [**Grands modèles de langage**]{.orange} (LLM)
  - ChatGPT, LLama2, Bard...
- Modèles de [**génération d'images**]{.orange}
  - Midjourney, Stable Diffusion, Dall-E
- Modèles [**Deep fake**]{.orange} : 
  - Exemple  <!-- TODO: trouver exemples -->


## ... créant de nouvelles problématiques

- Défi démocratique
- Gestions des droits d'auteurs :
  - Litige [GoT-OpenAI](https://www.liberation.fr/economie/medias/droits-dauteur-lauteur-de-game-of-thrones-attaque-openai-et-chatgpt-en-justice-20230921_Y2CMN4CKKVCOLHRDNS7W6ZA2AA/)
  - Poursuites [Stability AI/ Midjourney]()
- Failles de sécurité ([Samsung-OpenAI](https://www.bloomberg.com/news/articles/2023-05-02/samsung-bans-chatgpt-and-other-generative-ai-use-by-staff-after-leak?embedded-checkout=true))
- Réponses non sourcées
- Quid des données générées ?
