## 7 juin 1951

- Contexte :
  - :drapeau: Loi Française, promulguée en 1951.


## Loi informatique et liberté 1978

- Contexte :
  - :drapeau: Loi Française, promulguée en 1978.


## Loi pour une République Numérique

- Contexte :
  - :drapeau: Loi Française, promulguée en 2016.
  - :emojy croissance: Réponse à l'expansion rapide du numérique dans la société.
  - ⚖️ Equilibre entre innovation, inclusion, protection et confiance.

## Circulation des données et du savoir

- L'[**ouverture des données publiques**]{.orange} par défaut : 
  - L'État, les collectivités locales... et l'Insee !
  - Code sources et bases de données, sous condition d'anonymisation.
  - [CADA](https://www.cada.fr) et [CNIL](https://www.cnil.fr/fr) pour la mise en oeuvre des règles.

- Création d'un [**service public de la données**]{.orange} Etalab.
- [**Libre accès**]{.orange} des papiers académique financés à +50% par fond public.
- Ouverture des [**données d'intérêt général**]{.orange} (transports, eau, déchets, consommation d'énergie...).

## La protection des droits dans la société numérique

- Principe de la [**neutralité de l’internet**]{.orange} inscrit dans le droit français ➡️ [Arcep](https://www.arcep.fr)
- 3 obligations des plateformes en ligne : [**loyauté**]{.orange}, [**clarté**]{.orange} et [**transparence**]{.orange}
- Protection de la vie privée sur internet :
  - Droit à l'[**oubli numérique**]{.blue2}
  - Droit à la [**mort numérique**]{.blue2}
  - Règle du [**secret des correspondances privées**]{.blue2} (https://www.legifrance.gouv.fr/jorf/id/JORFTEXT000034307602)

## L’accès au numérique pour tous

- Le numérique dans tous les territoires :
  - Couverture 4G + sanctions opérateurs
- Le numérique au bénéfice des publics fragiles

https://www.vie-publique.fr/eclairage/20301-loi-republique-numerique-7-octobre-2016-loi-lemaire-quels-changements

## Règlement Général sur la Protection des Données (RGPD) de l'UE : 

https://fr.wikipedia.org/wiki/R%C3%A8glement_g%C3%A9n%C3%A9ral_sur_la_protection_des_donn%C3%A9es#

e-privacy => loi spéciale

## Big Data Act : 

https://digital-strategy.ec.europa.eu/fr/policies/data-act

