## Big Data, késako ?  {auto-animate=true}

- [**Big Data**]{.orange} : [*"Gestion et analyse d'un volume massif de données, souvent à une échelle bien supérieure à ce que les systèmes traditionnels peuvent traiter efficacement."*]{.blue2}

- [**Les 3 V**]{.orange} qui caractérise le Big Data :
    - [**Volume**]{.blue2} : le Big Data se réfère à des [**quantités énormes**]{.green2} de données [**générées en continu**]{.green2} ($\geq 10^{12} bits$)
    - [**Vitesse**]{.blue2} : vitesse à laquelle les données sont générées, collectées et traitées
    - [**Variété**]{.blue2} : le Big Data est généralement caractérisé par une [**diversité de sources**]{.green2} et de [**formats de données**]{.green2}

## Big Data, késako ?  {auto-animate=true}

- [**2 autres V**]{.orange} caractéristiques du Big Data :
    - [**Véracité**]{.blue2} : cela concerne la [**qualité**]{.green2}, la [**fiabilité**]{.green2} et l'[**authenticité**]{.green2} des données
    - [**Valeur**]{.blue2} : quelle valeur peut-elle être créer de l'analyse de ces données ?
 
<!-- - [**Exemples**]{.orange}  : 
    - contenus internet et de réseaux sociaux
    - images satellites
    - enregistrements automatiques (données de téléphonie, données de CB...) -->

## Le Big Data au service de la Statistique Publique

- Pourquoi s'intéresser au Big Data dans la statistique publique ?

- Plusieurs bénéfices peuvent en être retirer en matière d'[**efficience économique**]{.orange}, de [**qualité statistique**]{.orange}, de [**méthodologie statistique**]{.orange} ou encore d'[**exhaustivité**]{.orange}

## Le Big Data au service de la Statistique Publique


- [**Efficience économique**]{.orange} : Accès plus rapide à la données, réduction du coût des enquêtes
- [**Qualité statistique**]{.orange} : Données plus localisées, plus précises sur des sous-population, plus fréquentes...
- [**Méthodologie statistique**]{.orange} : Applications de nouvelles méthodes statistiques performantes sur des données massives (ML, deeplearning)... 
- [**Exhaustivité**]{.orange} : Données pouvant compléter des déclarations d'enquêtes, créer de nouveaux indicateurs...

## Des données très différentes des statistiques publiques usuelles


- [**Processus de génération**]{.orange} des données n'est pas contrôlé
- Problème de [**représentativité**]{.orange} des différentes sous population dans les données
- Formats généralement [**complexes**]{.orange} et souvent [**changeants**]{.orange} ou non pérennes
- [**Pertinence**]{.orange} et [**complétude**]{.orange} des données parfois douteuse

::: {.callout-important}
## Différence centrale
Les données massives ne sont ni collectées ni conceptualisées à des fins de statistiques publiques !
:::

## Innovations nécessaires pour traiter ces données

- [**Techniques**]{.orange} : nouveaux langages de datascience, nouvelles infrastructures informatiques 
- [**Méthodologiques**]{.orange} : économétrie en grande dimension, analyse de données textuelles, analyse d'images
- [**Organisationnelles**]{.orange} : Partenariats avec de nouveaux acteurs privés ou publics pour le partage de données


Le terme de big data recouvre un ensemble de sources très disparates
Le domaine des prix est celui où elles apparaissent les plus prometteuses.
Il s’agit d’un domaine où elles se présentent sous une forme relativement structurée,
assez similaire à celles des données administratives que la statistique publique a l’habitude de
manipuler, et l’objet de la mesure est conceptuellement simple.

Pour les autres choses : 
On est au plus dans une logique de complémentarité avec la production existante, que l’objectif soit d’aider à en
raccourcir les délais de publication, ou d’alléger la charge de réponse des unités enquêtées.

l’accès à des données quasi exhaustives permet d’envisager la production de statistiques très localisées ou centrées sur des catégories de population très spécifiques
Mais deux problèmes apparaissent alors. D’une part, la question de la protection de
la vie privée et du respect du secret des affaires.
L’accès à ces données doit pouvoir s’inscrire dans un cadre juridique clair
et durable.
Dans le
cas français, c’est la loi pour la République numérique qui a instauré le cadre juridique
nécessaire à cette garantie.
Ce qui remplace enquete on a le droit de demander
