## Conclusion

Le terme de big data recouvre un ensemble de sources très disparates
Le domaine des prix est celui où elles apparaissent les plus prometteuses.
Il s’agit d’un domaine où elles se présentent sous une forme relativement structurée,
assez similaire à celles des données administratives que la statistique publique a l’habitude de
manipuler, et l’objet de la mesure est conceptuellement simple.

Pour les autres choses : 
On est au plus dans une logique de complémentarité avec la production existante, que l’objectif soit d’aider à en
raccourcir les délais de publication, ou d’alléger la charge de réponse des unités enquêtées.

l’accès à des données quasi exhaustives permet d’envisager la production de statistiques très localisées ou centrées sur des catégories de population très spécifiques
Mais deux problèmes apparaissent alors. D’une part, la question de la protection de
la vie privée et du respect du secret des affaires.
L’accès à ces données doit pouvoir s’inscrire dans un cadre juridique clair
et durable.
Dans le
cas français, c’est la loi pour la République numérique qui a instauré le cadre juridique
nécessaire à cette garantie.
Ce qui remplace enquete on a le droit de demander
